### ISSUE TITLE
Unexpected [

### ISSUE THREAD

**Issue by hellomrdavis** [BrightcoveOS/php-wrapper-dynamic-ingest#1]
Hello, 

I'm attempting to incorporate the wrapper into a Wordpress plugin and I'm running into an error whenever I add `require 'dist/bc-diapi.php'; ` to the page. Below is what prints out when I turn on errors.

Parse error: syntax error, unexpected '[', expecting ')' in /var/www/html/wp-content/plugins/ndms-video/dist/bc-diapi.php on line 525

Thoughts?

**Comment by hellomrdavis** [comment]
Turns out we didn't have PHP 5.4+. That should solve the issue.

**Comment by rcrooks** [comment]
@hellomrdavis Let me know if not. The key PHP modules you need are curl and json

**Comment by hellomrdavis** [comment]
@rcrooks Thanks. If not able to upgrade our PHP version, is there are a past version of the wrapper available? Or, do you know what was the latest version of the AWS SDK that could be used for 5.3 and below?

**Comment by rcrooks** [comment]
@hellomrdavis This is the first and only version of the wrapper. The current version of the AWS SDK requires PHP 5.5+ -- for older versions of the AWS SDK (I have not tested with them), go to https://aws.amazon.com/sdk-for-php/ and scroll down awhile
